### PR TITLE
Bugfix eslint enhance

### PR DESCRIPTION
**Pull request by jeffrey-l-turner**
I've noticed a few problems with `typeof` not being used on compares with `undefined`. I fixed those as well as updated the eslint config. We're still having difficulties with getting ads to properly load without a hard refresh. Basically, the iframes that are coming back are empty when we switch between React components on our pages. We're still debugging this so please consider this Work in Progress.

### CODE REVIEW

**Comment by jaanauati** [comment]
Hi @jeffrey-l-turner!, is this ready for review?

**Comment by jeffrey-l-turner** [comment]
> Hi @jeffrey-l-turner!, is this ready for review?

I think this is probably safe to merge but to be frank we abandoned using `react-dfp` in our project and I really don't have time to devote more time to it at this point.

**Comment by jaanauati** [comment]
@jeffrey-l-turner thank u.

**Comment by jaanauati** [comment]
This is throwing bunch of errors when running the linter, given that it's not longer needed and I don't have the time to review and finish the work i'm closing the pr out. We can re-open it later if needed, thanks.

**Pull request closed without merging**
